source 'https://rubygems.org'

gem 'activesupport'
gem 'chronic'
gem 'cinch', git: 'https://github.com/gizmokid2005/cinch'
gem 'easypost'
gem 'ffaker'
gem 'mechanize'
gem 'nokogiri'
gem 'rubocop', group: 'development'
gem 'sinatra'
gem 'sqlite3'
gem 'thin'

# gem 'open-weather-ruby-client'
# gem 'openweathermap'
gem 'owmo'
